@startuml
skinparam componentStyle rectangle
skinparam packageStyle rectangle

' Client web
package "«Client»" {
    [Application web]
}

' TourGuide API
package "TourGuide\nAPI" {

    [TourGuide Controller]

    package "«Service»" {
        [TourGuideService]
        [RewardService]
    }

    package "«Model»" {
    }
}

' Util
package "Util" {
}

' Librairies
package "«librairie»" {
    [gpsUtil]
    [RewardCentral]
    [TripPricer]
}


' Relations
[Application web] --> [TourGuide Controller] : requêtes\nHTTP

[TourGuide Controller] --> [TourGuideService]
[TourGuide Controller] --> [RewardService]

[TourGuide\nAPI] ..> [gpsUtil] : Use
[TourGuide\nAPI] ..> [RewardCentral] : Use
[TourGuide\nAPI] ..> [TripPricer] : Use
[Service] <--> [Model]
[TourGuideService] ..> [Util]

@enduml